TOPICS = {
    'architecture': ['architecture', 'built environment',
                     'public spaces', 'offices', 'cities and towns',
                     'urban planning', 'architecture and technology',
                     'smart cities', 'urbanism', 'architectural design',
                     'modern architecture', 'architectural theory',
                     'experimental architecture', 'city planning',
                     'architecture -- human factors',
                     'architecture -- speculative',
                     'architecture and society -- congresses',
                     'city planning -- united states',
                     'modern architecture -- philosophy',
                     'space (architecture) -- philosophy', 'planning',
                     'modern movement (architecture) -- great britain'],
    'cognition': ['cognitive science', 'cognitive neuroscience',
                  'brain science', 'mind', 'neuroscience', 'memory',
                  'neurology', 'perception', 'psychology', 'brain',
                  'consciousness', 'theory of mind', 'comparative psychology',
                  'cognition', 'philosophy of mind', 'cognitive psychology',
                  'thought and thinking', 'space perception', 'brain damage',
                  'philosophy of mind--congresses', 'linguistics',
                  'human behavior', 'senses and sensation', 'mind and body',
                  'symbolism (psychology)'],
    'society': ['ideology', 'social behavior', 'game theory',
                'sociology', 'cooperation', 'altruism', 'social theory',
                'public opinion', 'justice', 'society', 'anthropology',
                'social networks', 'social sciences', 'social movements',
                'power (social sciences)', 'critical theory', 'sex role',
                'information society', 'social psychology', 'networks',
                'online social networks -- united states', 'language and languages',
                'civilization', 'social groups'],
    'media': ['media history', 'culture', 'communications',
              'media theory', 'cultural studies', 'media studies',
              'memetics', 'spectacle', 'memes', 'propaganda', 'social media',
              'mass media', 'communication', 'mass communication'],
    'art': ['art', 'conceptual art', 'psychedelic art', 'aesthetics',
            'computer art', 'electronic music', 'media art', 'dance',
            'modern art', 'art and society', 'artists\' books',
            'art and technology', 'modern art -- 21st century -- history and criticism',
            'art and globalization', 'european art--20th century',
            'music--philosophy and aesthetics', 'multimedia (art) -- exhibitions',
            'computer art -- europe -- exhibitions',
            'modern art -- 21st century -- exhibitions'],
    'economics': ['economics', 'capitalism', 'global financial crisis'],
    'politics': ['politics', 'political economy', 'radicalism',
                 'counterculture', 'utopias'],
    'systems': ['dynamic systems', 'chaos theory', 'systems',
                'systems theory', 'cybernetics', 'complexity (philosophy)',
                'mathematics', 'forecasting'],
    'war': ['technology and war', 'war (philosophy)'],
    'biology': ['genetics', 'evolution', 'biology--methodology',
                'biology', 'psychobiology', 'molecular biology',
                'sociobiology', 'drugs -- physiological effect',
                'adaptation (biology)', 'neurophysiology -- dictionaries',
                'environmental protection', 'neuropharmacology'],
    'computation': ['bitcoin', 'encryption', 'computer', 'data',
                    'computers', 'computer science', 'robotics',
                    'computation', 'artificial intelligence',
                    'computer networks', 'software', 'information',
                    'technology and civilization', 'machine learning',
                    'electronics', 'electronic data processing', 'simulation'],
    'humanities': ['philosophy', 'libraries', 'speculative fiction',
                   'fiction', 'literature', 'oral history', 'science fiction',
                   'supernatural -- fiction', 'religion', 'pedagogy'],
    'science': ['science', 'science -- philosophy'],
    'business': ['organizational behavior', 'business', 'management',
                 'complex organizations', 'leadership'],
    'design': ['human-computer interaction', 'design',
               'computer-aided design', 'user-centered design',
               'human-centered design', 'digital design',
               'engineering design', 'industrial design -- psychological aspects']
}
TAG_TO_TOPIC = {}
for topic, tags in TOPICS.items():
    for tag in tags:
        TAG_TO_TOPIC[tag] = topic

